language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
install:
 - python setup.py -q develop
 - pip install pytest pytest-cov
 # Install unittest2 on 2.6
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: py.test --cov skosprovider_sqlalchemy
